# OneVault Internal Admin Platform Configuration
# This configuration defines the tenant setup for the internal OneVault administration platform

platform_info:
  name: "onevault"
  display_name: "OneVault Admin Platform"
  type: "internal"
  description: "Internal administration platform for OneVault operations"
  
tenant_details:
  tenant_bk: "onevault"
  tenant_type: "internal"
  contact_email: "onevault@onevault.com"
  contact_phone: "+1-555-100-0001"
  contact_address: "OneVault HQ, 123 Innovation Drive"
  contact_city: "Tech City"
  contact_state: "CA"
  contact_zip: "12345"
  contact_country: "US"

# Define all users needed for this platform
users:
  - email: "admin@onevault.com"
    password: "AdminOV2025!"
    first_name: "OneVault"
    last_name: "Admin"
    phone: "+1-555-100-0002"
    job_title: "Platform Administrator"
    role: "ADMINISTRATOR"
    description: "Primary administrator for OneVault platform"
    
  - email: "support@onevault.com"
    password: "SupportOV2025!"
    first_name: "Support"
    last_name: "Team"
    phone: "+1-555-100-0003"
    job_title: "Support Manager"
    role: "MANAGER"
    description: "Customer support and user management"
    
  - email: "developer@onevault.com"
    password: "DevOV2025!"
    first_name: "Development"
    last_name: "Team"
    phone: "+1-555-100-0004"
    job_title: "Lead Developer"
    role: "ADMINISTRATOR"
    description: "Development team access for platform management"
    
  - email: "analytics@onevault.com"
    password: "AnalyticsOV2025!"
    first_name: "Analytics"
    last_name: "Team"
    phone: "+1-555-100-0005"
    job_title: "Data Analyst"
    role: "MANAGER"
    description: "Data analytics and reporting access"

# API key configuration
api_key:
  name: "onevault_platform_key"
  description: "Platform-level API key for OneVault internal operations"
  expiration_interval: "1 year"
  scopes:
    - "read"
    - "write"
    - "admin"
    - "system_health"
    - "audit_access"
    - "tenant_management"
    - "user_management"

# Security settings
security:
  enforce_mfa: true
  session_timeout_minutes: 30
  password_expiry_days: 90
  audit_all_actions: true
  
# Integration settings
integrations:
  environment_variables:
    - name: "ONEVAULT_ADMIN_API_KEY"
      description: "Internal admin API key"
    - name: "ONEVAULT_ADMIN_BASE_URL"
      value: "https://admin.onevault.com"
    - name: "ONEVAULT_AUDIT_LEVEL"
      value: "DETAILED"

# Monitoring and alerts
monitoring:
  health_checks: true
  performance_monitoring: true
  security_alerts: true
  usage_analytics: true
  
# Setup order (customize as needed)
setup_steps:
  1: "Create tenant with admin user"
  2: "Clear audit conflicts"
  3: "Create support team user"
  4: "Create developer team user"
  5: "Create analytics team user"
  6: "Generate platform API key"
  7: "Run final verification"
  8: "Configure monitoring and alerts" 