# OneVault Canvas Visual Workflow Builder Configuration
# This configuration defines the tenant setup for the OneVault Canvas platform

platform_info:
  name: "onevault_canvas"
  display_name: "OneVault Canvas"
  type: "internal"
  description: "Visual workflow builder for AI agent orchestration"
  
tenant_details:
  tenant_bk: "onevault_canvas"
  tenant_type: "internal"
  contact_email: "canvas@onevault.com"
  contact_phone: "+1-555-200-0001"
  contact_address: "OneVault Canvas Division, 456 Innovation Boulevard"
  contact_city: "Tech City"
  contact_state: "CA"
  contact_zip: "12345"
  contact_country: "US"

# Define all users needed for this platform
users:
  - email: "admin@onevault-canvas.com"
    password: "CanvasAdmin2025!"
    first_name: "Canvas"
    last_name: "Administrator"
    phone: "+1-555-200-0002"
    job_title: "Canvas Platform Administrator"
    role: "ADMINISTRATOR"
    description: "Primary administrator for Canvas workflow platform"
    
  - email: "demo@onevault-canvas.com"
    password: "CanvasDemo2025!"
    first_name: "Demo"
    last_name: "User"
    phone: "+1-555-200-0003"
    job_title: "Demo Account"
    role: "USER"
    description: "Demo account for showcasing Canvas capabilities"
    
  - email: "developer@onevault-canvas.com"
    password: "CanvasDev2025!"
    first_name: "Canvas"
    last_name: "Developer"
    phone: "+1-555-200-0004"
    job_title: "Canvas Developer"
    role: "ADMINISTRATOR"
    description: "Development team access for Canvas platform"
    
  - email: "workflow-designer@onevault-canvas.com"
    password: "WorkflowDesign2025!"
    first_name: "Workflow"
    last_name: "Designer"
    phone: "+1-555-200-0005"
    job_title: "AI Workflow Designer"
    role: "MANAGER"
    description: "Workflow design and template creation"

# API key configuration
api_key:
  name: "onevault_canvas_platform_key"
  description: "Platform-level API key for OneVault Canvas workflow operations"
  expiration_interval: "1 year"
  scopes:
    - "read"
    - "write"
    - "ai_chat"
    - "canvas_workflows"
    - "site_events"
    - "ai_sessions"
    - "workflow_execution"

# Security settings
security:
  enforce_mfa: false  # More lenient for demo/canvas use
  session_timeout_minutes: 60  # Longer sessions for workflow building
  password_expiry_days: 180
  audit_all_actions: true
  
# Canvas-specific settings
canvas_settings:
  max_nodes_per_workflow: 100
  max_workflows_per_user: 50
  auto_save_interval_seconds: 30
  collaboration_enabled: true
  version_control_enabled: true
  
# Integration settings
integrations:
  environment_variables:
    - name: "ONEVAULT_CANVAS_API_KEY"
      description: "Canvas platform API key"
    - name: "ONEVAULT_CANVAS_BASE_URL"
      value: "https://canvas.onevault.com"
    - name: "CANVAS_AI_ENDPOINT"
      value: "https://api.onevault.com/ai"
    - name: "CANVAS_EXECUTION_MODE"
      value: "REAL_TIME"

# Feature flags for Canvas
features:
  ai_node_types: true
  data_source_connectors: true
  real_time_collaboration: true
  workflow_templates: true
  performance_analytics: true
  export_import_workflows: true
  advanced_debugging: true

# Monitoring and alerts
monitoring:
  workflow_execution_tracking: true
  performance_metrics: true
  user_activity_analytics: true
  error_reporting: true
  resource_usage_monitoring: true
  
# Canvas-specific integrations
ai_integrations:
  supported_models:
    - "gpt-4"
    - "gpt-3.5-turbo"
    - "claude-3"
    - "custom_models"
  
  node_types:
    - "ai_chat"
    - "data_transform"
    - "decision_logic"
    - "api_connector"
    - "notification"
    - "schedule_trigger"
    - "webhook_listener"

# Setup order (customize as needed)
setup_steps:
  1: "Create Canvas tenant with admin user"
  2: "Clear audit conflicts"
  3: "Create demo user for presentations"
  4: "Create developer user"
  5: "Create workflow designer user"
  6: "Generate Canvas platform API key"
  7: "Run final verification"
  8: "Configure Canvas-specific features"
  9: "Set up workflow templates"
  10: "Test AI node integrations"

# Demo workflows to create
demo_workflows:
  - name: "Horse Health Analysis"
    description: "AI-powered horse health assessment workflow"
    complexity: "intermediate"
    
  - name: "Simple Data Processing"
    description: "Basic data input → transform → output workflow"
    complexity: "beginner"
    
  - name: "Multi-AI Collaboration"
    description: "Multiple AI models working together on a task"
    complexity: "advanced" 